Repository googleapis/go-genproto, pull requests merged in 2020-12, with the labels that each got.

#500 feat(all): auto-regenerate .pb.go files
  googleapis/cloud/osconfig/agentendpoint/v1/tasks.pb.go
  googleapis/cloud/osconfig/agentendpoint/v1beta/tasks.pb.go
  googleapis/cloud/retail/v2/catalog.pb.go
  googleapis/cloud/retail/v2/catalog_service.pb.go
  googleapis/cloud/retail/v2/common.pb.go
  googleapis/cloud/retail/v2/import_config.pb.go
  googleapis/cloud/retail/v2/prediction_service.pb.go
  googleapis/cloud/retail/v2/product.pb.go
  googleapis/cloud/retail/v2/product_service.pb.go
  googleapis/cloud/retail/v2/purge_config.pb.go
  googleapis/cloud/retail/v2/user_event.pb.go
  googleapis/cloud/retail/v2/user_event_service.pb.go
  googleapis/cloud/retail/v2alpha/catalog.pb.go
  googleapis/cloud/retail/v2alpha/catalog_service.pb.go
  googleapis/cloud/retail/v2alpha/common.pb.go
  googleapis/cloud/retail/v2alpha/import_config.pb.go
  googleapis/cloud/retail/v2alpha/prediction_service.pb.go
  googleapis/cloud/retail/v2alpha/product.pb.go
  googleapis/cloud/retail/v2alpha/product_service.pb.go
  googleapis/cloud/retail/v2alpha/purge_config.pb.go
  googleapis/cloud/retail/v2alpha/user_event.pb.go
  googleapis/cloud/retail/v2alpha/user_event_service.pb.go
  googleapis/cloud/retail/v2beta/catalog.pb.go
  googleapis/cloud/retail/v2beta/catalog_service.pb.go
  googleapis/cloud/retail/v2beta/common.pb.go
  googleapis/cloud/retail/v2beta/import_config.pb.go
  googleapis/cloud/retail/v2beta/prediction_service.pb.go
  googleapis/cloud/retail/v2beta/product.pb.go
  googleapis/cloud/retail/v2beta/product_service.pb.go
  googleapis/cloud/retail/v2beta/purge_config.pb.go
  googleapis/cloud/retail/v2beta/user_event.pb.go
  googleapis/cloud/retail/v2beta/user_event_service.pb.go
  googleapis/cloud/vision/v1/image_annotator.pb.go
  googleapis/cloud/vision/v1p1beta1/image_annotator.pb.go
  googleapis/cloud/vision/v1p2beta1/image_annotator.pb.go
  googleapis/cloud/vision/v1p3beta1/image_annotator.pb.go
  googleapis/cloud/vision/v1p4beta1/image_annotator.pb.go
  googleapis/container/v1beta1/cluster_service.pb.go
  googleapis/logging/v2/logging.pb.go
  googleapis/maps/routes/v1/compute_route_matrix_request.pb.go
  googleapis/maps/routes/v1/polyline.pb.go
  googleapis/maps/routes/v1/route_matrix_element.pb.go
  googleapis/maps/routes/v1/route_service.pb.go
  googleapis/maps/routes/v1/toll_passes.pb.go
  googleapis/maps/routes/v1alpha/route_service.pb.go
  googleapis/spanner/admin/database/v1/spanner_database_admin.pb.go
  regen.txt
Labels: cla: yes

#501 feat(all): auto-regenerate .pb.go files
  googleapis/cloud/asset/v1/asset_service.pb.go
  regen.txt
Labels: cla: yes

#502 feat(all): auto-regenerate .pb.go files
  googleapis/actions/sdk/v2/actions_sdk.pb.go
  googleapis/actions/sdk/v2/interactionmodel/prompt/static_media_prompt.pb.go
  googleapis/actions/sdk/v2/release_channel.pb.go
  googleapis/actions/sdk/v2/settings.pb.go
  googleapis/actions/sdk/v2/version.pb.go
  googleapis/cloud/dataproc/v1beta2/autoscaling_policies.pb.go
  googleapis/cloud/dataproc/v1beta2/clusters.pb.go
  googleapis/cloud/dataproc/v1beta2/jobs.pb.go
  googleapis/cloud/dataproc/v1beta2/shared.pb.go
  googleapis/cloud/dataproc/v1beta2/workflow_templates.pb.go
  regen.txt
Labels: automerge, cla: yes

#503 feat(all): auto-regenerate .pb.go files
  googleapis/analytics/data/v1alpha/analytics_data_api.pb.go
  googleapis/analytics/data/v1alpha/data.pb.go
  googleapis/cloud/accessapproval/v1/accessapproval.pb.go
  googleapis/cloud/bigquery/storage/v1beta2/storage.pb.go
  googleapis/cloud/bigquery/storage/v1beta2/stream.pb.go
  googleapis/cloud/channel/v1/channel_partner_links.pb.go
  googleapis/cloud/channel/v1/common.pb.go
  googleapis/cloud/channel/v1/customers.pb.go
  googleapis/cloud/channel/v1/entitlements.pb.go
  googleapis/cloud/channel/v1/offers.pb.go
  googleapis/cloud/channel/v1/operations.pb.go
  googleapis/cloud/channel/v1/products.pb.go
  googleapis/cloud/channel/v1/service.pb.go
  googleapis/cloud/dialogflow/v2beta1/agent.pb.go
  googleapis/cloud/dialogflow/v2beta1/document.pb.go
  googleapis/cloud/dialogflow/v2beta1/knowledge_base.pb.go
  googleapis/cloud/dialogflow/v2beta1/session.pb.go
  googleapis/cloud/osconfig/agentendpoint/v1/inventory.pb.go
  googleapis/cloud/retail/v2/import_config.pb.go
  googleapis/cloud/retail/v2/product.pb.go
  googleapis/cloud/retail/v2alpha/import_config.pb.go
  googleapis/cloud/retail/v2alpha/product.pb.go
  googleapis/cloud/retail/v2beta/import_config.pb.go
  googleapis/cloud/retail/v2beta/product.pb.go
  regen.txt
Labels: cla: yes

#504 feat(all): auto-regenerate .pb.go files
  googleapis/cloud/dialogflow/v2/agent.pb.go
  googleapis/cloud/dialogflow/v2/session.pb.go
  regen.txt
Labels: cla: yes

#505 feat(all): auto-regenerate .pb.go files
  googleapis/analytics/admin/v1alpha/resources.pb.go
  googleapis/cloud/dialogflow/cx/v3beta1/response_message.pb.go
  googleapis/cloud/dialogflow/cx/v3beta1/session.pb.go
  googleapis/cloud/videointelligence/v1/video_intelligence.pb.go
  regen.txt
Labels: automerge, cla: yes

#506 feat(all): auto-regenerate .pb.go files
  googleapis/cloud/channel/v1/entitlements.pb.go
  googleapis/cloud/channel/v1/products.pb.go
  googleapis/cloud/channel/v1/service.pb.go
  googleapis/cloud/retail/v2/catalog.pb.go
  googleapis/cloud/retail/v2/prediction_service.pb.go
  googleapis/cloud/retail/v2/product.pb.go
  googleapis/cloud/retail/v2/product_service.pb.go
  googleapis/cloud/retail/v2alpha/catalog.pb.go
  googleapis/cloud/retail/v2alpha/prediction_service.pb.go
  googleapis/cloud/retail/v2alpha/product.pb.go
  googleapis/cloud/retail/v2alpha/product_service.pb.go
  googleapis/cloud/retail/v2beta/catalog.pb.go
  googleapis/cloud/retail/v2beta/prediction_service.pb.go
  googleapis/cloud/retail/v2beta/product.pb.go
  googleapis/cloud/retail/v2beta/product_service.pb.go
  regen.txt
Labels: cla: yes

#507 feat(all): auto-regenerate .pb.go files
  googleapis/api/annotations/field_behavior.pb.go
  googleapis/api/serviceconfig/auth.pb.go
  googleapis/api/serviceconfig/endpoint.pb.go
  googleapis/api/serviceconfig/service.pb.go
  googleapis/cloud/networkconnectivity/v1alpha1/common.pb.go
  googleapis/cloud/networkconnectivity/v1alpha1/hub.pb.go
  regen.txt
Labels: cla: yes

#508 feat!(asset): remove v1beta1
  googleapis/cloud/asset/v1beta1/asset_service.pb.go
  googleapis/cloud/asset/v1beta1/assets.pb.go
Labels: api: cloudasset, cla: yes
