Repository googleapis/go-genproto, pull requests merged in 2022-09, with the labels that each got.

#890 chore(all): auto-regenerate .pb.go files
  googleapis/cloud/aiplatform/v1beta1/batch_prediction_job.pb.go
  googleapis/cloud/batch/v1/job.pb.go
  googleapis/cloud/batch/v1alpha/job.pb.go
  googleapis/cloud/bigquery/dataexchange/v1beta1/dataexchange.pb.go
  googleapis/cloud/bigquery/datapolicies/v1beta1/datapolicy.pb.go
  googleapis/cloud/certificatemanager/logging/v1/logs.pb.go
  googleapis/cloud/websecurityscanner/v1/scan_run_log.pb.go
  googleapis/maps/fleetengine/delivery/v1/delivery_api.pb.go
  googleapis/maps/fleetengine/delivery/v1/delivery_vehicles.pb.go
  googleapis/maps/fleetengine/delivery/v1/tasks.pb.go
  googleapis/maps/fleetengine/v1/fleetengine.pb.go
  googleapis/maps/fleetengine/v1/trip_api.pb.go
  googleapis/maps/fleetengine/v1/trips.pb.go
  googleapis/maps/fleetengine/v1/vehicle_api.pb.go
  googleapis/maps/fleetengine/v1/vehicles.pb.go
  googleapis/maps/routing/v2/routing_preference.pb.go
  googleapis/maps/routing/v2/waypoint.pb.go
  regen.txt
Labels: breaking change

#911 chore(all): auto-regenerate .pb.go files
  googleapis/api/expr/v1alpha1/checked.pb.go
  googleapis/api/expr/v1alpha1/eval.pb.go
  googleapis/api/expr/v1alpha1/explain.pb.go
  googleapis/api/expr/v1alpha1/syntax.pb.go
  googleapis/api/expr/v1alpha1/value.pb.go
  googleapis/apps/drive/activity/v2/action.pb.go
  googleapis/apps/drive/activity/v2/actor.pb.go
  googleapis/apps/drive/activity/v2/common.pb.go
  googleapis/apps/drive/activity/v2/drive_activity_service.pb.go
  googleapis/apps/drive/activity/v2/query_drive_activity_request.pb.go
  googleapis/apps/drive/activity/v2/query_drive_activity_response.pb.go
  googleapis/apps/drive/activity/v2/target.pb.go
  googleapis/bigtable/v2/bigtable.pb.go
  googleapis/bigtable/v2/request_stats.pb.go
  googleapis/cloud/aiplatform/v1/batch_prediction_job.pb.go
  googleapis/cloud/aiplatform/v1/custom_job.pb.go
  googleapis/cloud/aiplatform/v1/featurestore_service.pb.go
  googleapis/cloud/aiplatform/v1/job_service.pb.go
  googleapis/cloud/aiplatform/v1/metadata_service.pb.go
  googleapis/cloud/aiplatform/v1/model.pb.go
  googleapis/cloud/aiplatform/v1/pipeline_service.pb.go
  googleapis/cloud/dataproc/v1/clusters.pb.go
  googleapis/cloud/discoveryengine/v1beta/common.pb.go
  googleapis/cloud/discoveryengine/v1beta/document.pb.go
  googleapis/cloud/discoveryengine/v1beta/document_service.pb.go
  googleapis/cloud/discoveryengine/v1beta/import_config.pb.go
  googleapis/cloud/discoveryengine/v1beta/recommendation_service.pb.go
  googleapis/cloud/discoveryengine/v1beta/user_event.pb.go
  googleapis/cloud/discoveryengine/v1beta/user_event_service.pb.go
  googleapis/cloud/kubernetes/security/containersecurity_logging/logging.pb.go
  googleapis/cloud/language/v1/language_service.pb.go
  googleapis/cloud/sensitiveaction/logging/v1/sensitive_action_payload.pb.go
  googleapis/iam/v2/policy.pb.go
  googleapis/maps/fleetengine/delivery/v1/common.pb.go
  googleapis/maps/fleetengine/v1/fleetengine.pb.go
  googleapis/streetview/publish/v1/resources.pb.go
  googleapis/streetview/publish/v1/rpcmessages.pb.go
  googleapis/streetview/publish/v1/streetview_publish.pb.go
  regen.txt
Labels: breaking change

#913 chore(all): auto-regenerate .pb.go files
  googleapis/cloud/dataproc/v1/clusters.pb.go
  googleapis/cloud/deploy/v1/cloud_deploy.pb.go
  googleapis/cloud/deploy/v1/jobrun_notification_payload.pb.go
  googleapis/cloud/enterpriseknowledgegraph/v1/job_state.pb.go
  googleapis/cloud/enterpriseknowledgegraph/v1/operation_metadata.pb.go
  googleapis/cloud/enterpriseknowledgegraph/v1/service.pb.go
  regen.txt
Labels: breaking change allowed, breaking change

#914 chore(all): auto-regenerate alias files
  go.mod
  go.sum
  googleapis/cloud/aiplatform/v1beta1/alias.go
  googleapis/cloud/asset/v1p2beta1/alias.go
  googleapis/cloud/asset/v1p5beta1/alias.go
  googleapis/cloud/language/v1beta2/alias.go
  googleapis/cloud/security/publicca/v1beta1/alias.go
Labels: automerge
