Repository googleapis/go-genproto, pull requests merged in 2022-07, with the labels that each got.

#850 chore(all): auto-regenerate .pb.go files
  googleapis/cloud/commerce/consumer/procurement/v1alpha1/order.pb.go
  googleapis/cloud/commerce/consumer/procurement/v1alpha1/procurement_service.pb.go
  googleapis/cloud/stream/logging/v1/logging.pb.go
  regen.txt
Labels: breaking change

#853 chore(all): auto-regenerate .pb.go files
  googleapis/cloud/networkservices/v1/common.pb.go
  googleapis/cloud/networkservices/v1/endpoint_policy.pb.go
  googleapis/cloud/networkservices/v1/gateway.pb.go
  googleapis/cloud/networkservices/v1/grpc_route.pb.go
  googleapis/cloud/networkservices/v1/http_route.pb.go
  googleapis/cloud/networkservices/v1/mesh.pb.go
  googleapis/cloud/networkservices/v1/network_services.pb.go
  googleapis/cloud/networkservices/v1/service_binding.pb.go
  googleapis/cloud/networkservices/v1/tcp_route.pb.go
  googleapis/cloud/networkservices/v1/tls_route.pb.go
  regen.txt
Labels: breaking change

#856 chore(all): auto-regenerate .pb.go files
  googleapis/cloud/dataform/v1alpha2/dataform.pb.go
  googleapis/cloud/networkmanagement/v1/connectivity_test.pb.go
  googleapis/cloud/networkmanagement/v1/reachability.pb.go
  googleapis/cloud/networkmanagement/v1/trace.pb.go
  googleapis/privacy/dlp/v2/dlp.pb.go
  googleapis/privacy/dlp/v2/storage.pb.go
  regen.txt
Labels: breaking change allowed, breaking change

#857 chore(all): auto-regenerate .pb.go files
  googleapis/cloud/bigquery/migration/v2/migration_entities.pb.go
  googleapis/cloud/bigquery/migration/v2/translation_config.pb.go
  googleapis/cloud/networksecurity/v1/authorization_policy.pb.go
  googleapis/cloud/networksecurity/v1/client_tls_policy.pb.go
  googleapis/cloud/networksecurity/v1/common.pb.go
  googleapis/cloud/networksecurity/v1/network_security.pb.go
  googleapis/cloud/networksecurity/v1/server_tls_policy.pb.go
  googleapis/cloud/networksecurity/v1/tls.pb.go
  googleapis/maps/fleetengine/delivery/v1/delivery_api.pb.go
  regen.txt
Labels: breaking change

#867 chore(storage): add warning in doc.go
  googleapis/storage/v2/doc.go
Labels: api: storage
